enum PreviewMode {
  DETECT_PREVIEW_MOTION_WHITE,
  DETECT_PREVIEW_MOTION_RED,
  DETECT_PREVIEW_MOTION_GREEN,
  DETECT_PREVIEW_MOTION_BLUE,
  DETECT_PREVIEW_MOTION_GRAYSCALE,
  DETECT_PREVIEW_MOTION_WHITE_WITH_BACKGROUND,
  DETECT_MOTION_LINES,
};

// Default preview mode
PreviewMode previewMode = PreviewMode::DETECT_PREVIEW_MOTION_WHITE;
PreviewMode previousPreviewMode = previewMode;
